### ISSUE TITLE
  // , Why is this incompatible with "spacemacs"?

### ISSUE THREAD

**Issue by v6** [jbranso/evil-dvorak#2]
// , I'm new to `evil-dvorak`, but I noticed that it doesn't seem to work with `spacemacs`: 

```
Loading /Users/nbasanes/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...done
evil-jumper has been integrated into evil-mode and is obsolete.
smooth-scrolling enabled.
(Spacemacs) --> deleting evil-dvorak... [1/2]
Spacemacs is ready.
Loading /Users/nbasanes/.emacs.d/.cache/recentf...done
Open the quickhelp.
```

**Comment by v6** [comment]
// , Plus, recovering from the error seems to require manual intervention beyond just reverting the changes to `~/.emacs.d/init.el`, as I describe here: 

http://stackoverflow.com/questions/36187765/why-does-emacs-attempt-to-use-local-share-in-osx-even-when-not-run-as-ro

**Comment by jbranso** [comment]
You can also look at this thread here: https://github.com/syl20bnr/spacemacs/issues/2443    And I'm not a user of spacemacs, but doesn't it by default delete packages unless you explicitly whitelist the ones you want to keep?

**Comment by StreakyCobra** [comment]
@v6 If you want to install an extra package in Spacemacs, you have to add it to the `dotspacemacs-additionnal-packages` list and restart, otherwise it will be deleted if you install it manually.

I'm not sure `evil-dvorak` will work out of the box with Spacemacs, but we will try to integrate some dvorak support in Spacemacs soon.

**Comment by v6** [comment]
@jbranso, it tries to delete it, but as you can see in the code I posted and in my post to stackoverflow.com, the deletion fails, and breaks the init.el configuration.

**Comment by v6** [comment]
@StreakyCobra, I'm going to have another go with Spacemacs and evil-dvorak once I can get the damn thing to even start up properly. 

I reverted my init.el configuration, but Spacemacs is still dead. This attempt to install a package without using dotspacemacs-additional-packages seems to have broken Spacemacs.

**Comment by jbranso** [comment]
So I believe that OSX is using ~/.local/share, because that is where emacs assumes your $HOME variable is set, which doesn't make much sense, since OSX is unix based and $HOME should be ~/.  Hmmm.  I would highly recommend you to use freedom respecting operating system.  You might find one that you like here: http://www.gnu.org/distros/free-distros.html Also,  @v6 true, did you do what StreakyCobra recommended?  "If you want to install an extra package in Spacemacs, you have to add it to the dotspacemacs-additionnal-packages list and restart, otherwise it will be deleted if you install it manually."  Also look at https://github.com/syl20bnr/spacemacs/issues/2443, which tells you that my evil-dvorak currently does not work well with spacemacs anyway, but I am currently working on improving this situation.  When my evil-dvorak mode gets some updates, the maintainers of spacemacs will try to incorporate those changes into a new spacemacs layer.  :)

**Comment by jbranso** [comment]
I've recently updated evil-dvorak to be much more light-weight.  It's only dependency now is evil-mode.   You might give it a try again and see if it works with spacemacs now.

**Comment by StreakyCobra** [comment]
@v6 https://github.com/syl20bnr/spacemacs/issues/2443#issuecomment-210897655 If you want the steps to enable it.
